spring.application.name=springBatch
spring.profiles.active=default

spring.data.mongo.host=localhost
spring.data.mongo.port=27017
spring.data.mongo.database=spingbatch_db
spring.batch.job.enable=false
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:mem:users;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enable=true
#spring.batch.initialize-schema=always
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:org/springframework/batch/core/schema-h2.sql

# ? Spring Batch still needs this
spring.batch.initialize-schema=never

